# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Westside Audio
    url: https://www.westsideaudio-sg.com
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: http://westsideaudio-sg.com/wp-content/uploads/2024/11/vinyl1.png
  name: Upptime
  introTitle: "**Westside Audio** uptime monitor and status page, powered by Upptime."
  introMessage: This is an uptime monitor configured for our Westside Audio website. Shop for your audio and vinyl needs today!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.westsideaudio-sg.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
